sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
  global:
  # - STACK=1.0.0.0
  - SMT=z3
  # - GHC=ghc-7.10.3
  - ARGS="--resolver nightly"
  matrix:
  - TESTS=Unit/
  - TESTS=Benchmarks/text
  - TESTS=Benchmarks/bytestring
  - TESTS=Benchmarks/esop
  - TESTS=Benchmarks/vect-algs
  - TESTS=Benchmarks/icfp*

 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script: stack --pedantic $ARGS --no-terminal --install-ghc test --haddock --test-arguments "-p $TESTS"

# install:
#  - scripts/travis install_smt "$SMT"
#  - scripts/travis install_stack "$STACK"
#  - scripts/travis configure_stack "$GHC"
#  - scripts/travis setup_ghc
#  - scripts/travis install_dependencies
# 
# script:
#  - scripts/travis do_build && scripts/travis do_test "$TESTS" "$SMT"

after_failure:
 - scripts/travis dump_fail_logs

notifications:
  slack:
    rooms:
      secure: CPaI+XVTUSM9gLQefB8zSXazawNIaUnClS7FwaujPfM37hNBm5UIoiC80KBEe0KZKBr+Gt/LWq0zv506Zl/vILuPpVmfSi2BQ8zyyKCBbUrE/E0uBTjmT7wjaITf/mn3mqiLLcHbAVXI1bn7HzVvAq4S4eIpttgCapF7pbMhZCk=
    on_success: change
    on_failure: always
    on_start: never
